#pragma once

namespace ShitEditor
{
    static constexpr char LICENSE[] = R"(MIT License

Copyright (c) 2026 Majjcom

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.)";

    static constexpr char OPENSOURCE_PROJECTS[] =
        "--------------------\n"
        "1. SDL (https://www.libsdl.org/)\n"
        "\n"
        "Copyright (C) 1997-2024 Sam Lantinga <slouken@libsdl.org>\n"
        "  \n"
        "This software is provided 'as-is', without any express or implied\n"
        "warranty.  In no event will the authors be held liable for any damages\n"
        "arising from the use of this software.\n"
        "\n"
        "Permission is granted to anyone to use this software for any purpose,\n"
        "including commercial applications, and to alter it and redistribute it\n"
        "freely, subject to the following restrictions:\n"
        "  \n"
        "1. The origin of this software must not be misrepresented; you must not\n"
        "   claim that you wrote the original software. If you use this software\n"
        "   in a product, an acknowledgment in the product documentation would be\n"
        "   appreciated but is not required. \n"
        "2. Altered source versions must be plainly marked as such, and must not be\n"
        "   misrepresented as being the original software.\n"
        "3. This notice may not be removed or altered from any source distribution.\n"
        "\n"
        "--------------------\n"
        "2. GmSSL (http://gmssl.org/)\n"
        "\n"
        "                                 Apache License\n"
        "                           Version 2.0, January 2004\n"
        "                        http://www.apache.org/licenses/\n"
        "\n"
        "   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n"
        "\n"
        "   1. Definitions.\n"
        "\n"
        "      \"License\" shall mean the terms and conditions for use, reproduction,\n"
        "      and distribution as defined by Sections 1 through 9 of this document.\n"
        "\n"
        "      \"Licensor\" shall mean the copyright owner or entity authorized by\n"
        "      the copyright owner that is granting the License.\n"
        "\n"
        "      \"Legal Entity\" shall mean the union of the acting entity and all\n"
        "      other entities that control, are controlled by, or are under common\n"
        "      control with that entity. For the purposes of this definition,\n"
        "      \"control\" means (i) the power, direct or indirect, to cause the\n"
        "      direction or management of such entity, whether by contract or\n"
        "      otherwise, or (ii) ownership of fifty percent (50%) or more of the\n"
        "      outstanding shares, or (iii) beneficial ownership of such entity.\n"
        "\n"
        "      \"You\" (or \"Your\") shall mean an individual or Legal Entity\n"
        "      exercising permissions granted by this License.\n"
        "\n"
        "      \"Source\" form shall mean the preferred form for making modifications,\n"
        "      including but not limited to software source code, documentation\n"
        "      source, and configuration files.\n"
        "\n"
        "      \"Object\" form shall mean any form resulting from mechanical\n"
        "      transformation or translation of a Source form, including but\n"
        "      not limited to compiled object code, generated documentation,\n"
        "      and conversions to other media types.\n"
        "\n"
        "      \"Work\" shall mean the work of authorship, whether in Source or\n"
        "      Object form, made available under the License, as indicated by a\n"
        "      copyright notice that is included in or attached to the work\n"
        "      (an example is provided in the Appendix below).\n"
        "\n"
        "      \"Derivative Works\" shall mean any work, whether in Source or Object\n"
        "      form, that is based on (or derived from) the Work and for which the\n"
        "      editorial revisions, annotations, elaborations, or other modifications\n"
        "      represent, as a whole, an original work of authorship. For the purposes\n"
        "      of this License, Derivative Works shall not include works that remain\n"
        "      separable from, or merely link (or bind by name) to the interfaces of,\n"
        "      the Work and Derivative Works thereof.\n"
        "\n"
        "      \"Contribution\" shall mean any work of authorship, including\n"
        "      the original version of the Work and any modifications or additions\n"
        "      to that Work or Derivative Works thereof, that is intentionally\n"
        "      submitted to Licensor for inclusion in the Work by the copyright owner\n"
        "      or by an individual or Legal Entity authorized to submit on behalf of\n"
        "      the copyright owner. For the purposes of this definition, \"submitted\"\n"
        "      means any form of electronic, verbal, or written communication sent\n"
        "      to the Licensor or its representatives, including but not limited to\n"
        "      communication on electronic mailing lists, source code control systems,\n"
        "      and issue tracking systems that are managed by, or on behalf of, the\n"
        "      Licensor for the purpose of discussing and improving the Work, but\n"
        "      excluding communication that is conspicuously marked or otherwise\n"
        "      designated in writing by the copyright owner as \"Not a Contribution.\"\n"
        "\n"
        "      \"Contributor\" shall mean Licensor and any individual or Legal Entity\n"
        "      on behalf of whom a Contribution has been received by Licensor and\n"
        "      subsequently incorporated within the Work.\n"
        "\n"
        "   2. Grant of Copyright License. Subject to the terms and conditions of\n"
        "      this License, each Contributor hereby grants to You a perpetual,\n"
        "      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n"
        "      copyright license to reproduce, prepare Derivative Works of,\n"
        "      publicly display, publicly perform, sublicense, and distribute the\n"
        "      Work and such Derivative Works in Source or Object form.\n"
        "\n"
        "   3. Grant of Patent License. Subject to the terms and conditions of\n"
        "      this License, each Contributor hereby grants to You a perpetual,\n"
        "      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n"
        "      (except as stated in this section) patent license to make, have made,\n"
        "      use, offer to sell, sell, import, and otherwise transfer the Work,\n"
        "      where such license applies only to those patent claims licensable\n"
        "      by such Contributor that are necessarily infringed by their\n"
        "      Contribution(s) alone or by combination of their Contribution(s)\n"
        "      with the Work to which such Contribution(s) was submitted. If You\n"
        "      institute patent litigation against any entity (including a\n"
        "      cross-claim or counterclaim in a lawsuit) alleging that the Work\n"
        "      or a Contribution incorporated within the Work constitutes direct\n"
        "      or contributory patent infringement, then any patent licenses\n"
        "      granted to You under this License for that Work shall terminate\n"
        "      as of the date such litigation is filed.\n"
        "\n"
        "   4. Redistribution. You may reproduce and distribute copies of the\n"
        "      Work or Derivative Works thereof in any medium, with or without\n"
        "      modifications, and in Source or Object form, provided that You\n"
        "      meet the following conditions:\n"
        "\n"
        "      (a) You must give any other recipients of the Work or\n"
        "          Derivative Works a copy of this License; and\n"
        "\n"
        "      (b) You must cause any modified files to carry prominent notices\n"
        "          stating that You changed the files; and\n"
        "\n"
        "      (c) You must retain, in the Source form of any Derivative Works\n"
        "          that You distribute, all copyright, patent, trademark, and\n"
        "          attribution notices from the Source form of the Work,\n"
        "          excluding those notices that do not pertain to any part of\n"
        "          the Derivative Works; and\n"
        "\n"
        "      (d) If the Work includes a \"NOTICE\" text file as part of its\n"
        "          distribution, then any Derivative Works that You distribute must\n"
        "          include a readable copy of the attribution notices contained\n"
        "          within such NOTICE file, excluding those notices that do not\n"
        "          pertain to any part of the Derivative Works, in at least one\n"
        "          of the following places: within a NOTICE text file distributed\n"
        "          as part of the Derivative Works; within the Source form or\n"
        "          documentation, if provided along with the Derivative Works; or,\n"
        "          within a display generated by the Derivative Works, if and\n"
        "          wherever such third-party notices normally appear. The contents\n"
        "          of the NOTICE file are for informational purposes only and\n"
        "          do not modify the License. You may add Your own attribution\n"
        "          notices within Derivative Works that You distribute, alongside\n"
        "          or as an addendum to the NOTICE text from the Work, provided\n"
        "          that such additional attribution notices cannot be construed\n"
        "          as modifying the License.\n"
        "\n"
        "      You may add Your own copyright statement to Your modifications and\n"
        "      may provide additional or different license terms and conditions\n"
        "      for use, reproduction, or distribution of Your modifications, or\n"
        "      for any such Derivative Works as a whole, provided Your use,\n"
        "      reproduction, and distribution of the Work otherwise complies with\n"
        "      the conditions stated in this License.\n"
        "\n"
        "   5. Submission of Contributions. Unless You explicitly state otherwise,\n"
        "      any Contribution intentionally submitted for inclusion in the Work\n"
        "      by You to the Licensor shall be under the terms and conditions of\n"
        "      this License, without any additional terms or conditions.\n"
        "      Notwithstanding the above, nothing herein shall supersede or modify\n"
        "      the terms of any separate license agreement you may have executed\n"
        "      with Licensor regarding such Contributions.\n"
        "\n"
        "   6. Trademarks. This License does not grant permission to use the trade\n"
        "      names, trademarks, service marks, or product names of the Licensor,\n"
        "      except as required for reasonable and customary use in describing the\n"
        "      origin of the Work and reproducing the content of the NOTICE file.\n"
        "\n"
        "   7. Disclaimer of Warranty. Unless required by applicable law or\n"
        "      agreed to in writing, Licensor provides the Work (and each\n"
        "      Contributor provides its Contributions) on an \"AS IS\" BASIS,\n"
        "      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or\n"
        "      implied, including, without limitation, any warranties or conditions\n"
        "      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A\n"
        "      PARTICULAR PURPOSE. You are solely responsible for determining the\n"
        "      appropriateness of using or redistributing the Work and assume any\n"
        "      risks associated with Your exercise of permissions under this License.\n"
        "\n"
        "   8. Limitation of Liability. In no event and under no legal theory,\n"
        "      whether in tort (including negligence), contract, or otherwise,\n"
        "      unless required by applicable law (such as deliberate and grossly\n"
        "      negligent acts) or agreed to in writing, shall any Contributor be\n"
        "      liable to You for damages, including any direct, indirect, special,\n"
        "      incidental, or consequential damages of any character arising as a\n"
        "      result of this License or out of the use or inability to use the\n"
        "      Work (including but not limited to damages for loss of goodwill,\n"
        "      work stoppage, computer failure or malfunction, or any and all\n"
        "      other commercial damages or losses), even if such Contributor\n"
        "      has been advised of the possibility of such damages.\n"
        "\n"
        "   9. Accepting Warranty or Additional Liability. While redistributing\n"
        "      the Work or Derivative Works thereof, You may choose to offer,\n"
        "      and charge a fee for, acceptance of support, warranty, indemnity,\n"
        "      or other liability obligations and/or rights consistent with this\n"
        "      License. However, in accepting such obligations, You may act only\n"
        "      on Your own behalf and on Your sole responsibility, not on behalf\n"
        "      of any other Contributor, and only if You agree to indemnify,\n"
        "      defend, and hold each Contributor harmless for any liability\n"
        "      incurred by, or claims asserted against, such Contributor by reason\n"
        "      of your accepting any such warranty or additional liability.\n"
        "\n"
        "   END OF TERMS AND CONDITIONS\n"
        "\n"
        "--------------------\n"
        "3. glad (https://github.com/Olgardos/glad)\n"
        "\n"
        "The glad source code:\n"
        "\n"
        "    The MIT License (MIT)\n"
        "\n"
        "    Copyright (c) 2013-2021 David Herberth\n"
        "\n"
        "    Permission is hereby granted, free of charge, to any person obtaining a copy of\n"
        "    this software and associated documentation files (the \"Software\"), to deal in\n"
        "    the Software without restriction, including without limitation the rights to\n"
        "    use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of\n"
        "    the Software, and to permit persons to whom the Software is furnished to do so,\n"
        "    subject to the following conditions:\n"
        "\n"
        "    The above copyright notice and this permission notice shall be included in all\n"
        "    copies or substantial portions of the Software.\n"
        "\n"
        "    THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "    IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS\n"
        "    FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR\n"
        "    COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER\n"
        "    IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN\n"
        "    CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
        "\n"
        "\n"
        "The Khronos Specifications:\n"
        "\n"
        "    Copyright (c) 2013-2020 The Khronos Group Inc.\n"
        "\n"
        "    Licensed under the Apache License, Version 2.0 (the \"License\");\n"
        "    you may not use this file except in compliance with the License.\n"
        "    You may obtain a copy of the License at\n"
        "\n"
        "        http://www.apache.org/licenses/LICENSE-2.0\n"
        "\n"
        "    Unless required by applicable law or agreed to in writing, software\n"
        "    distributed under the License is distributed on an \"AS IS\" BASIS,\n"
        "    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
        "    See the License for the specific language governing permissions and\n"
        "    limitations under the License.\n"
        "\n"
        "\n"
        "The EGL Specification and various headers:\n"
        "\n"
        "    Copyright (c) 2007-2016 The Khronos Group Inc.\n"
        "\n"
        "    Permission is hereby granted, free of charge, to any person obtaining a\n"
        "    copy of this software and/or associated documentation files (the\n"
        "    \"Materials\"), to deal in the Materials without restriction, including\n"
        "    without limitation the rights to use, copy, modify, merge, publish,\n"
        "    distribute, sublicense, and/or sell copies of the Materials, and to\n"
        "    permit persons to whom the Materials are furnished to do so, subject to\n"
        "    the following conditions:\n"
        "\n"
        "    The above copyright notice and this permission notice shall be included\n"
        "    in all copies or substantial portions of the Materials.\n"
        "\n"
        "    THE MATERIALS ARE PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n"
        "    EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n"
        "    MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.\n"
        "    IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY\n"
        "    CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\n"
        "    TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE\n"
        "    MATERIALS OR THE USE OR OTHER DEALINGS IN THE MATERIALS.\n"
        "\n"
        "--------------------\n"
        "4. Zlib (https://www.zlib.net/)\n"
        "\n"
        "Copyright notice:\n"
        "\n"
        " (C) 1995-2022 Jean-loup Gailly and Mark Adler\n"
        "\n"
        "  This software is provided 'as-is', without any express or implied\n"
        "  warranty.  In no event will the authors be held liable for any damages\n"
        "  arising from the use of this software.\n"
        "\n"
        "  Permission is granted to anyone to use this software for any purpose,\n"
        "  including commercial applications, and to alter it and redistribute it\n"
        "  freely, subject to the following restrictions:\n"
        "\n"
        "  1. The origin of this software must not be misrepresented; you must not\n"
        "     claim that you wrote the original software. If you use this software\n"
        "     in a product, an acknowledgment in the product documentation would be\n"
        "     appreciated but is not required.\n"
        "  2. Altered source versions must be plainly marked as such, and must not be\n"
        "     misrepresented as being the original software.\n"
        "  3. This notice may not be removed or altered from any source distribution.\n"
        "\n"
        "  Jean-loup Gailly        Mark Adler\n"
        "  jloup@gzip.org          madler@alumni.caltech.edu\n"
        "\n"
        "--------------------\n"
        "5. glm (https://github.com/icaven/glm)\n"
        "\n"
        "================================================================================\n"
        "OpenGL Mathematics (GLM)\n"
        "--------------------------------------------------------------------------------\n"
        "GLM is licensed under The Happy Bunny License or MIT License\n"
        "\n"
        "================================================================================\n"
        "The Happy Bunny License (Modified MIT License)\n"
        "--------------------------------------------------------------------------------\n"
        "Copyright (c) 2005 - G-Truc Creation\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "Restrictions:\n"
        " By making use of the Software for military purposes, you choose to make a\n"
        " Bunny unhappy.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
        "THE SOFTWARE.\n"
        "\n"
        "================================================================================\n"
        "The MIT License\n"
        "--------------------------------------------------------------------------------\n"
        "Copyright (c) 2005 - G-Truc Creation\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
        "THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "6. Lua (https://www.lua.org/)\n"
        "\n"
        "Copyright © 1994–2023 Lua.org, PUC-Rio.\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
        "THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "7. RapidJSON (https://rapidjson.org/)\n"
        "\n"
        "Tencent is pleased to support the open source community by making RapidJSON available. \n"
        " \n"
        "Copyright (C) 2015 THL A29 Limited, a Tencent company, and Milo Yip.  All rights reserved.\n"
        "\n"
        "If you have downloaded a copy of the RapidJSON binary from Tencent, please note\n"
        "that the RapidJSON binary is licensed under the MIT License.\n"
        "\n"
        "If you have downloaded a copy of the RapidJSON source code from Tencent, please note\n"
        "that RapidJSON source code is licensed under the MIT License, except for the third-party\n"
        "components listed below which are subject to different license terms.  Your integration\n"
        "of RapidJSON into your own projects may require compliance with the MIT License,\n"
        "as well as the other licenses applicable to the third-party components included within\n"
        "RapidJSON. To avoid the problematic JSON license in your own projects, it's sufficient\n"
        "to exclude the bin/jsonchecker/ directory, as it's the only code under the JSON license\n"
        "\n"
        "A copy of the MIT License is included in this file.\n"
        "\n"
        "Other dependencies and licenses:\n"
        "\n"
        "Open Source Software Licensed Under the BSD License:\n"
        "--------------------------------------------------------------------\n"
        "\n"
        "The msinttypes r29 \n"
        "Copyright (c) 2006-2013 Alexander Chemeris \n"
        "All rights reserved.\n"
        "\n"
        "Redistribution and use in source and binary forms, with or without modification, are\n"
        "permitted provided that the following conditions are met:\n"
        "\n"
        "* Redistributions of source code must retain the above copyright notice, this list of\n"
        "conditions and the following disclaimer. \n"
        "\n"
        "* Redistributions in binary form must reproduce the above copyright notice, this list\n"
        "of conditions and the following disclaimer in the documentation and/or other materials\n"
        "provided with the distribution.\n"
        "\n"
        "* Neither the name of  copyright holder nor the names of its contributors may be used\n"
        "to endorse or promote products derived from this software without specific prior written\n"
        "permission.\n"
        "\n"
        "THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND ANY EXPRESS OR\n"
        "IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF\n"
        "MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL\n"
        "THE REGENTS AND CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,\n"
        "EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF\n"
        "SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)\n"
        "HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\n"
        "OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS\n"
        "SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        "\n"
        "Open Source Software Licensed Under the JSON License:\n"
        "--------------------------------------------------------------------\n"
        "\n"
        "json.org \n"
        "Copyright (c) 2002 JSON.org\n"
        "All Rights Reserved.\n"
        "\n"
        "JSON_checker\n"
        "Copyright (c) 2002 JSON.org\n"
        "All Rights Reserved.\n"
        "\n"
        "	\n"
        "Terms of the JSON License:\n"
        "---------------------------------------------------\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy of this\n"
        "software and associated documentation files (the \"Software\"), to deal in the Software\n"
        "without restriction, including without limitation the rights to use, copy, modify,\n"
        "merge, publish, distribute, sublicense, and/or sell copies of the Software, and to\n"
        "permit persons to whom the Software is furnished to do so, subject to the following\n"
        "conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all copies\n"
        "or substantial portions of the Software.\n"
        "\n"
        "The Software shall be used for Good, not Evil.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\n"
        "INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR\n"
        "PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\n"
        "LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,\n"
        "TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE\n"
        "OR OTHER DEALINGS IN THE SOFTWARE.\n"
        "\n"
        "\n"
        "Terms of the MIT License:\n"
        "--------------------------------------------------------------------\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy of this\n"
        "software and associated documentation files (the \"Software\"), to deal in the Software\n"
        "without restriction, including without limitation the rights to use, copy, modify, merge,\n"
        "publish, distribute, sublicense, and/or sell copies of the Software, and to permit\n"
        "persons to whom the Software is furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all copies\n"
        "or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,\n"
        "INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR\n"
        "PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE\n"
        "FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR\n"
        "OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
        "DEALINGS IN THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "8. box2d (https://box2d.org/)\n"
        "\n"
        "MIT License\n"
        "\n"
        "Copyright (c) 2022 Erin Catto\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "9. imgui (https://github.com/ocornut/imgui)\n"
        "\n"
        "The MIT License (MIT)\n"
        "\n"
        "Copyright (c) 2014-2024 Omar Cornut\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "10. ogg (https://github.com/xiph/ogg)\n"
        "\n"
        "Copyright (c) 2002, Xiph.org Foundation\n"
        "\n"
        "Redistribution and use in source and binary forms, with or without\n"
        "modification, are permitted provided that the following conditions\n"
        "are met:\n"
        "\n"
        "- Redistributions of source code must retain the above copyright\n"
        "notice, this list of conditions and the following disclaimer.\n"
        "\n"
        "- Redistributions in binary form must reproduce the above copyright\n"
        "notice, this list of conditions and the following disclaimer in the\n"
        "documentation and/or other materials provided with the distribution.\n"
        "\n"
        "- Neither the name of the Xiph.org Foundation nor the names of its\n"
        "contributors may be used to endorse or promote products derived from\n"
        "this software without specific prior written permission.\n"
        "\n"
        "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
        "``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
        "LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
        "A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION\n"
        "OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
        "SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
        "LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
        "DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
        "THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        "(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
        "OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        "\n"
        "--------------------\n"
        "11. vorbis (https://github.com/xiph/vorbis)\n"
        "\n"
        "Copyright (c) 2002-2020 Xiph.org Foundation\n"
        "\n"
        "Redistribution and use in source and binary forms, with or without\n"
        "modification, are permitted provided that the following conditions\n"
        "are met:\n"
        "\n"
        "- Redistributions of source code must retain the above copyright\n"
        "notice, this list of conditions and the following disclaimer.\n"
        "\n"
        "- Redistributions in binary form must reproduce the above copyright\n"
        "notice, this list of conditions and the following disclaimer in the\n"
        "documentation and/or other materials provided with the distribution.\n"
        "\n"
        "- Neither the name of the Xiph.org Foundation nor the names of its\n"
        "contributors may be used to endorse or promote products derived from\n"
        "this software without specific prior written permission.\n"
        "\n"
        "THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS\n"
        "``AS IS'' AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT\n"
        "LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR\n"
        "A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE FOUNDATION\n"
        "OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,\n"
        "SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT\n"
        "LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,\n"
        "DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY\n"
        "THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT\n"
        "(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
        "OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
        "\n"
        "--------------------\n"
        "12. mimalloc (https://github.com/microsoft/mimalloc)\n"
        "\n"
        "MIT License\n"
        "\n"
        "Copyright (c) 2018-2021 Microsoft Corporation, Daan Leijen\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "13. Boost\n"
        "\n"
        "Boost Software License - Version 1.0 - August 17th, 2003\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person or organization\n"
        "obtaining a copy of the software and accompanying documentation covered by\n"
        "this license (the \"Software\") to use, reproduce, display, distribute,\n"
        "execute, and transmit the Software, and to prepare derivative works of the\n"
        "Software, and to permit third-parties to whom the Software is furnished to\n"
        "do so, all subject to the following:\n"
        "\n"
        "The copyright notices in the Software and this entire statement, including\n"
        "the above license grant, this restriction and the following disclaimer,\n"
        "must be included in all copies of the Software, in whole or in part, and\n"
        "all derivative works of the Software, unless such copies or derivative\n"
        "works are solely in the form of machine-executable object code generated by\n"
        "a source language processor.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT\n"
        "SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE\n"
        "FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,\n"
        "ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
        "DEALINGS IN THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "14. GmSSL-Java (https://github.com/GmSSL/GmSSL-Java)\n"
        "\n"
        "                                 Apache License\n"
        "                           Version 2.0, January 2004\n"
        "                        http://www.apache.org/licenses/\n"
        "\n"
        "   TERMS AND CONDITIONS FOR USE, REPRODUCTION, AND DISTRIBUTION\n"
        "\n"
        "   1. Definitions.\n"
        "\n"
        "      \"License\" shall mean the terms and conditions for use, reproduction,\n"
        "      and distribution as defined by Sections 1 through 9 of this document.\n"
        "\n"
        "      \"Licensor\" shall mean the copyright owner or entity authorized by\n"
        "      the copyright owner that is granting the License.\n"
        "\n"
        "      \"Legal Entity\" shall mean the union of the acting entity and all\n"
        "      other entities that control, are controlled by, or are under common\n"
        "      control with that entity. For the purposes of this definition,\n"
        "      \"control\" means (i) the power, direct or indirect, to cause the\n"
        "      direction or management of such entity, whether by contract or\n"
        "      otherwise, or (ii) ownership of fifty percent (50%) or more of the\n"
        "      outstanding shares, or (iii) beneficial ownership of such entity.\n"
        "\n"
        "      \"You\" (or \"Your\") shall mean an individual or Legal Entity\n"
        "      exercising permissions granted by this License.\n"
        "\n"
        "      \"Source\" form shall mean the preferred form for making modifications,\n"
        "      including but not limited to software source code, documentation\n"
        "      source, and configuration files.\n"
        "\n"
        "      \"Object\" form shall mean any form resulting from mechanical\n"
        "      transformation or translation of a Source form, including but\n"
        "      not limited to compiled object code, generated documentation,\n"
        "      and conversions to other media types.\n"
        "\n"
        "      \"Work\" shall mean the work of authorship, whether in Source or\n"
        "      Object form, made available under the License, as indicated by a\n"
        "      copyright notice that is included in or attached to the work\n"
        "      (an example is provided in the Appendix below).\n"
        "\n"
        "      \"Derivative Works\" shall mean any work, whether in Source or Object\n"
        "      form, that is based on (or derived from) the Work and for which the\n"
        "      editorial revisions, annotations, elaborations, or other modifications\n"
        "      represent, as a whole, an original work of authorship. For the purposes\n"
        "      of this License, Derivative Works shall not include works that remain\n"
        "      separable from, or merely link (or bind by name) to the interfaces of,\n"
        "      the Work and Derivative Works thereof.\n"
        "\n"
        "      \"Contribution\" shall mean any work of authorship, including\n"
        "      the original version of the Work and any modifications or additions\n"
        "      to that Work or Derivative Works thereof, that is intentionally\n"
        "      submitted to Licensor for inclusion in the Work by the copyright owner\n"
        "      or by an individual or Legal Entity authorized to submit on behalf of\n"
        "      the copyright owner. For the purposes of this definition, \"submitted\"\n"
        "      means any form of electronic, verbal, or written communication sent\n"
        "      to the Licensor or its representatives, including but not limited to\n"
        "      communication on electronic mailing lists, source code control systems,\n"
        "      and issue tracking systems that are managed by, or on behalf of, the\n"
        "      Licensor for the purpose of discussing and improving the Work, but\n"
        "      excluding communication that is conspicuously marked or otherwise\n"
        "      designated in writing by the copyright owner as \"Not a Contribution.\"\n"
        "\n"
        "      \"Contributor\" shall mean Licensor and any individual or Legal Entity\n"
        "      on behalf of whom a Contribution has been received by Licensor and\n"
        "      subsequently incorporated within the Work.\n"
        "\n"
        "   2. Grant of Copyright License. Subject to the terms and conditions of\n"
        "      this License, each Contributor hereby grants to You a perpetual,\n"
        "      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n"
        "      copyright license to reproduce, prepare Derivative Works of,\n"
        "      publicly display, publicly perform, sublicense, and distribute the\n"
        "      Work and such Derivative Works in Source or Object form.\n"
        "\n"
        "   3. Grant of Patent License. Subject to the terms and conditions of\n"
        "      this License, each Contributor hereby grants to You a perpetual,\n"
        "      worldwide, non-exclusive, no-charge, royalty-free, irrevocable\n"
        "      (except as stated in this section) patent license to make, have made,\n"
        "      use, offer to sell, sell, import, and otherwise transfer the Work,\n"
        "      where such license applies only to those patent claims licensable\n"
        "      by such Contributor that are necessarily infringed by their\n"
        "      Contribution(s) alone or by combination of their Contribution(s)\n"
        "      with the Work to which such Contribution(s) was submitted. If You\n"
        "      institute patent litigation against any entity (including a\n"
        "      cross-claim or counterclaim in a lawsuit) alleging that the Work\n"
        "      or a Contribution incorporated within the Work constitutes direct\n"
        "      or contributory patent infringement, then any patent licenses\n"
        "      granted to You under this License for that Work shall terminate\n"
        "      as of the date such litigation is filed.\n"
        "\n"
        "   4. Redistribution. You may reproduce and distribute copies of the\n"
        "      Work or Derivative Works thereof in any medium, with or without\n"
        "      modifications, and in Source or Object form, provided that You\n"
        "      meet the following conditions:\n"
        "\n"
        "      (a) You must give any other recipients of the Work or\n"
        "          Derivative Works a copy of this License; and\n"
        "\n"
        "      (b) You must cause any modified files to carry prominent notices\n"
        "          stating that You changed the files; and\n"
        "\n"
        "      (c) You must retain, in the Source form of any Derivative Works\n"
        "          that You distribute, all copyright, patent, trademark, and\n"
        "          attribution notices from the Source form of the Work,\n"
        "          excluding those notices that do not pertain to any part of\n"
        "          the Derivative Works; and\n"
        "\n"
        "      (d) If the Work includes a \"NOTICE\" text file as part of its\n"
        "          distribution, then any Derivative Works that You distribute must\n"
        "          include a readable copy of the attribution notices contained\n"
        "          within such NOTICE file, excluding those notices that do not\n"
        "          pertain to any part of the Derivative Works, in at least one\n"
        "          of the following places: within a NOTICE text file distributed\n"
        "          as part of the Derivative Works; within the Source form or\n"
        "          documentation, if provided along with the Derivative Works; or,\n"
        "          within a display generated by the Derivative Works, if and\n"
        "          wherever such third-party notices normally appear. The contents\n"
        "          of the NOTICE file are for informational purposes only and\n"
        "          do not modify the License. You may add Your own attribution\n"
        "          notices within Derivative Works that You distribute, alongside\n"
        "          or as an addendum to the NOTICE text from the Work, provided\n"
        "          that such additional attribution notices cannot be construed\n"
        "          as modifying the License.\n"
        "\n"
        "      You may add Your own copyright statement to Your modifications and\n"
        "      may provide additional or different license terms and conditions\n"
        "      for use, reproduction, or distribution of Your modifications, or\n"
        "      for any such Derivative Works as a whole, provided Your use,\n"
        "      reproduction, and distribution of the Work otherwise complies with\n"
        "      the conditions stated in this License.\n"
        "\n"
        "   5. Submission of Contributions. Unless You explicitly state otherwise,\n"
        "      any Contribution intentionally submitted for inclusion in the Work\n"
        "      by You to the Licensor shall be under the terms and conditions of\n"
        "      this License, without any additional terms or conditions.\n"
        "      Notwithstanding the above, nothing herein shall supersede or modify\n"
        "      the terms of any separate license agreement you may have executed\n"
        "      with Licensor regarding such Contributions.\n"
        "\n"
        "   6. Trademarks. This License does not grant permission to use the trade\n"
        "      names, trademarks, service marks, or product names of the Licensor,\n"
        "      except as required for reasonable and customary use in describing the\n"
        "      origin of the Work and reproducing the content of the NOTICE file.\n"
        "\n"
        "   7. Disclaimer of Warranty. Unless required by applicable law or\n"
        "      agreed to in writing, Licensor provides the Work (and each\n"
        "      Contributor provides its Contributions) on an \"AS IS\" BASIS,\n"
        "      WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or\n"
        "      implied, including, without limitation, any warranties or conditions\n"
        "      of TITLE, NON-INFRINGEMENT, MERCHANTABILITY, or FITNESS FOR A\n"
        "      PARTICULAR PURPOSE. You are solely responsible for determining the\n"
        "      appropriateness of using or redistributing the Work and assume any\n"
        "      risks associated with Your exercise of permissions under this License.\n"
        "\n"
        "   8. Limitation of Liability. In no event and under no legal theory,\n"
        "      whether in tort (including negligence), contract, or otherwise,\n"
        "      unless required by applicable law (such as deliberate and grossly\n"
        "      negligent acts) or agreed to in writing, shall any Contributor be\n"
        "      liable to You for damages, including any direct, indirect, special,\n"
        "      incidental, or consequential damages of any character arising as a\n"
        "      result of this License or out of the use or inability to use the\n"
        "      Work (including but not limited to damages for loss of goodwill,\n"
        "      work stoppage, computer failure or malfunction, or any and all\n"
        "      other commercial damages or losses), even if such Contributor\n"
        "      has been advised of the possibility of such damages.\n"
        "\n"
        "   9. Accepting Warranty or Additional Liability. While redistributing\n"
        "      the Work or Derivative Works thereof, You may choose to offer,\n"
        "      and charge a fee for, acceptance of support, warranty, indemnity,\n"
        "      or other liability obligations and/or rights consistent with this\n"
        "      License. However, in accepting such obligations, You may act only\n"
        "      on Your own behalf and on Your sole responsibility, not on behalf\n"
        "      of any other Contributor, and only if You agree to indemnify,\n"
        "      defend, and hold each Contributor harmless for any liability\n"
        "      incurred by, or claims asserted against, such Contributor by reason\n"
        "      of your accepting any such warranty or additional liability.\n"
        "\n"
        "   END OF TERMS AND CONDITIONS\n"
        "\n"
        "   APPENDIX: How to apply the Apache License to your work.\n"
        "\n"
        "      To apply the Apache License to your work, attach the following\n"
        "      boilerplate notice, with the fields enclosed by brackets \"[]\"\n"
        "      replaced with your own identifying information. (Don't include\n"
        "      the brackets!)  The text should be enclosed in the appropriate\n"
        "      comment syntax for the file format. We also recommend that a\n"
        "      file or class name and description of purpose be included on the\n"
        "      same \"printed page\" as the copyright notice for easier\n"
        "      identification within third-party archives.\n"
        "\n"
        "   Copyright [yyyy] [name of copyright owner]\n"
        "\n"
        "   Licensed under the Apache License, Version 2.0 (the \"License\");\n"
        "   you may not use this file except in compliance with the License.\n"
        "   You may obtain a copy of the License at\n"
        "\n"
        "       http://www.apache.org/licenses/LICENSE-2.0\n"
        "\n"
        "   Unless required by applicable law or agreed to in writing, software\n"
        "   distributed under the License is distributed on an \"AS IS\" BASIS,\n"
        "   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n"
        "   See the License for the specific language governing permissions and\n"
        "   limitations under the License.\n"
        "\n"
        "--------------------\n"
        "15. stb_image.h (https://github.com/nothings/stb/blob/master/stb_image.h)\n"
        "\n"
        "MIT License\n"
        "Copyright (c) 2017 Sean Barrett\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy of\n"
        "this software and associated documentation files (the \"Software\"), to deal in\n"
        "the Software without restriction, including without limitation the rights to\n"
        "use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies\n"
        "of the Software, and to permit persons to whom the Software is furnished to do\n"
        "so, subject to the following conditions:\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "16. robin-hood-hashing (https://github.com/martinus/robin-hood-hashing)\n"
        "\n"
        "MIT License\n"
        "\n"
        "Copyright (c) 2018-2021 Martin Ankerl\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "17. luasocket (https://github.com/lunarmodules/luasocket)\n"
        "\n"
        "Copyright (C) 2004-2022 Diego Nehab\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a\n"
        "copy of this software and associated documentation files (the \"Software\"),\n"
        "to deal in the Software without restriction, including without limitation\n"
        "the rights to use, copy, modify, merge, publish, distribute, sublicense,\n"
        "and/or sell copies of the Software, and to permit persons to whom the\n"
        "Software is furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING\n"
        "FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER\n"
        "DEALINGS IN THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "18. spdlog (https://github.com/gabime/spdlog)\n"
        "\n"
        "The MIT License (MIT)\n"
        "\n"
        "Copyright (c) 2016 Gabi Melman.                                       \n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
        "THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "19. fmt (https://github.com/fmtlib/fmt)\n"
        "\n"
        "Copyright (c) 2012 - present, Victor Zverovich and {fmt} contributors\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining\n"
        "a copy of this software and associated documentation files (the\n"
        "\"Software\"), to deal in the Software without restriction, including\n"
        "without limitation the rights to use, copy, modify, merge, publish,\n"
        "distribute, sublicense, and/or sell copies of the Software, and to\n"
        "permit persons to whom the Software is furnished to do so, subject to\n"
        "the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be\n"
        "included in all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND,\n"
        "EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF\n"
        "MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND\n"
        "NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE\n"
        "LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION\n"
        "OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION\n"
        "WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "20. MobDebug (https://github.com/pkulchenko/MobDebug)\n"
        "\n"
        "Copyright (C) 2011-2018 Paul Kulchenko\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
        "THE SOFTWARE.\n"
        "\n"
        "--[[ RemDebug License ]]---------------------------------------------------\n"
        "\n"
        "Copyright (c) 2006 The Kepler Project.\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
        "THE SOFTWARE.\n"
        "\n"
        "--[[ Serpent License ]]----------------------------------------------------\n"
        "\n"
        "Copyright (c) 2011-2013 Paul Kulchenko (paul@kulchenko.com)\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in\n"
        "all copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN\n"
        "THE SOFTWARE.\n"
        "\n"
        "--------------------\n"
        "21. ImGuiColorTextEdit (https://github.com/BalazsJako/ImGuiColorTextEdit)\n"
        "\n"
        "MIT License\n"
        "\n"
        "Copyright (c) 2017 BalazsJako\n"
        "\n"
        "Permission is hereby granted, free of charge, to any person obtaining a copy\n"
        "of this software and associated documentation files (the \"Software\"), to deal\n"
        "in the Software without restriction, including without limitation the rights\n"
        "to use, copy, modify, merge, publish, distribute, sublicense, and/or sell\n"
        "copies of the Software, and to permit persons to whom the Software is\n"
        "furnished to do so, subject to the following conditions:\n"
        "\n"
        "The above copyright notice and this permission notice shall be included in all\n"
        "copies or substantial portions of the Software.\n"
        "\n"
        "THE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\n"
        "IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\n"
        "FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\n"
        "AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\n"
        "LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\n"
        "OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\n"
        "SOFTWARE.\n";
}
